INSERT INTO personas (nombre,apellidos,dni) VALUES('OSCAR','NUÑEZ GUERRERO','02733910S');
INSERT INTO personas (nombre,apellidos,dni) VALUES('ENRIQUE','CASTILLO SERRANO','37534616L');
INSERT INTO personas (nombre,apellidos,dni) VALUES('PABLO','TORRES GARRIDO','83690756N');
INSERT INTO personas (nombre,apellidos,dni) VALUES('JOSE ANTONIO','RODRIGUEZ FERRER','48315097D');
INSERT INTO personas (nombre,apellidos,dni) VALUES('SEBASTIAN','JIMENEZ GOMEZ','55263823K');
INSERT INTO personas (nombre,apellidos,dni) VALUES('RUBEN','ROMERO PASTOR','52209918X');
INSERT INTO personas (nombre,apellidos,dni) VALUES('VICTOR MANUEL','RAMIREZ SOLER','98323392W');
INSERT INTO personas (nombre,apellidos,dni) VALUES('SAMUEL','DELGADO NIETO','07913589W');
INSERT INTO personas (nombre,apellidos,dni) VALUES('CRISTIAN','SANCHEZ GUERRERO','89146841Z');
INSERT INTO personas (nombre,apellidos,dni) VALUES('GUILLERMO','RAMOS MORA','41983840P');
INSERT INTO personas (nombre,apellidos,dni) VALUES('JULIO','JIMENEZ DIAZ','07763984N');
INSERT INTO personas (nombre,apellidos,dni) VALUES('JOSE FRANCISCO','LORENZO MENDEZ','05005273J');
INSERT INTO personas (nombre,apellidos,dni) VALUES('MIGUEL','SAEZ MUÑOZ','19985112K');
INSERT INTO personas (nombre,apellidos,dni) VALUES('JOSE','DURAN PRIETO','92864473H');
INSERT INTO personas (nombre,apellidos,dni) VALUES('HUGO','ALVAREZ SERRANO','05692157W');
INSERT INTO personas (nombre,apellidos,dni) VALUES('MARC','CABRERA MENDEZ','87640049K');
INSERT INTO personas (nombre,apellidos,dni) VALUES('JOSE RAMON','GALLEGO CASTRO','62886147F');
INSERT INTO personas (nombre,apellidos,dni) VALUES('JOSE FRANCISCO','MORA PRIETO','77744134V');
INSERT INTO personas (nombre,apellidos,dni) VALUES('MIGUEL ANGEL','DELGADO ROMAN','39205376J');
INSERT INTO personas (nombre,apellidos,dni) VALUES('JUAN MANUEL','VICENTE MARTIN','35297012Q');
INSERT INTO personas (nombre,apellidos,dni) VALUES('ENRIQUE','FERNANDEZ REYES','19609730E');
INSERT INTO personas (nombre,apellidos,dni) VALUES('SEBASTIAN','VARGAS HIDALGO','10636476B');
INSERT INTO personas (nombre,apellidos,dni) VALUES('ANTONIO','NAVARRO MOYA','13412337W');
INSERT INTO personas (nombre,apellidos,dni) VALUES('FELIPE','DOMINGUEZ MORALES','20835436N');
INSERT INTO personas (nombre,apellidos,dni) VALUES('JULIO','VAZQUEZ GALLARDO','60999331L');
INSERT INTO personas (nombre,apellidos,dni) VALUES('LUCAS','GIL PEÑA','19694822Z');
INSERT INTO personas (nombre,apellidos,dni) VALUES('RODRIGO','MUÑOZ CAMPOS','69722858Z');
INSERT INTO personas (nombre,apellidos,dni) VALUES('ISMAEL','ALONSO CALVO','28778161D');
INSERT INTO personas (nombre,apellidos,dni) VALUES('SALVADOR','PARRA CRUZ','39100258M');
INSERT INTO personas (nombre,apellidos,dni) VALUES('JORGE','MOLINA ESTEBAN','70999792B');
INSERT INTO personas (nombre,apellidos,dni) VALUES('FERNANDO','PASTOR MUÑOZ','97627441P');
INSERT INTO personas (nombre,apellidos,dni) VALUES('HECTOR','ROMERO BLANCO','32923778Z');
INSERT INTO personas (nombre,apellidos,dni) VALUES('SERGIO','DURAN BRAVO','19055710A');
INSERT INTO personas (nombre,apellidos,dni) VALUES('CARLOS','LOPEZ VARGAS','92299415R');
INSERT INTO personas (nombre,apellidos,dni) VALUES('JUAN','REYES PEREZ','53654126W');
INSERT INTO personas (nombre,apellidos,dni) VALUES('AITOR','SOTO CARMONA','62238051M');
INSERT INTO personas (nombre,apellidos,dni) VALUES('JOSEP','VARGAS VEGA','11182503H');
INSERT INTO personas (nombre,apellidos,dni) VALUES('ALBERT','HERRERO LEON','97233914B');
INSERT INTO personas (nombre,apellidos,dni) VALUES('RICARDO','SOLER SOLER','54014006R');
INSERT INTO personas (nombre,apellidos,dni) VALUES('ALBERT','RODRIGUEZ GIMENEZ','68888588T');
INSERT INTO personas (nombre,apellidos,dni) VALUES('LUIS MIGUEL','MARTIN MARIN','96603291W');
INSERT INTO personas (nombre,apellidos,dni) VALUES('VICTOR','GOMEZ MORENO','60809065D');
INSERT INTO personas (nombre,apellidos,dni) VALUES('RAMON','JIMENEZ VEGA','37035118N');
INSERT INTO personas (nombre,apellidos,dni) VALUES('ALFONSO','CARRASCO TORRES','06263340A');
INSERT INTO personas (nombre,apellidos,dni) VALUES('SALVADOR','PASTOR DURAN','66179847S');
INSERT INTO personas (nombre,apellidos,dni) VALUES('FRANCISCO JOSE','SANTANA CARMONA','57276170Y');
INSERT INTO personas (nombre,apellidos,dni) VALUES('CESAR','ROJAS CALVO','21186310K');
INSERT INTO personas (nombre,apellidos,dni) VALUES('GONZALO','VEGA RUIZ','95299712V');
INSERT INTO personas (nombre,apellidos,dni) VALUES('ALFREDO','GOMEZ CANO','28927291F');
INSERT INTO personas (nombre,apellidos,dni) VALUES('JOSE MANUEL','ALONSO MONTERO','36352778J');
