package dev.xarlsr.popdb;

import java.util.ArrayList;
import java.util.List;

public class Parameters {

    /**
     * Defines the max number of lines (rows) of SQL filling code to be generated
     * by the app.
     */
    public static final int MAX_ROWS = 1000;

    /**
     * Defines a list of the field types available to handle.
     */
    public static final List<String> FIELD_TYPES = List.of
            ("DATE", "DNI", "DSTRING", "FSTRING", "GSTRING");

    /**
     * Defines the list of fields descriptions. Descriptions MUST be in the same order
     * as the fields are in FIELD_TYPES list.
     */
    public static final List<String> FIELD_DESC = List.of
            (
            "Value is a generated random date between two dates.",
            "Value is auto generated corresponding to an spanish DNI -8 numbers + 1 control character",
            "Value is generated by reading and concatenating 2 random strings from a text file ",
            "Value is generated by reading 1 random string from a text file ",
            "Value is auto generated randomly with the pattern entered by user");
}
